language: scala

scala:
  - 2.11.8
  - 2.12.0-RC1

jdk:
  - oraclejdk8

before_install:
  - ./install-redis.sh

env:
  global:
    - REDIS_VERSION=3.2.2
    - REDIS_HOME=$PWD/redis-$REDIS_VERSION/src

script:
  - sbt "plz $TRAVIS_SCALA_VERSION clean" "plz $TRAVIS_SCALA_VERSION test"

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - redis-$REDIS_VERSION

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

notifications:
  email:
    - r.janusz@avsystem.com
