language: scala

scala:
  - 2.11.8
  - 2.12.0-RC2

jdk:
  - oraclejdk8

script:
  - sbt "plz $TRAVIS_SCALA_VERSION test" "plz $TRAVIS_SCALA_VERSION doc"

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete