language: scala

scala:
  - 2.12.11
  - 2.13.1

jdk:
  - openjdk8

before_install:
  - ./install-redis.sh

env:
  global:
    - REDIS_VERSION=5.0.0
    - REDIS_HOME=$PWD/redis-$REDIS_VERSION/src
  matrix:
    - TASK="commons-jvm/test"
    - TASK="commons-js/test"
    - TASK="commons/unidoc"

script:
  - sbt ++$TRAVIS_SCALA_VERSION $TASK

jobs:
  include:
    - stage: deploy
      script: if [ "$TRAVIS_PULL_REQUEST" = 'false' ]; then ./deploy.sh; fi
      if: tag =~ ^v

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.cache/
    - $HOME/.sbt/
    - $HOME/.m2/
    - redis-$REDIS_VERSION

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

notifications:
  email:
    - r.janusz@avsystem.com
