language: scala

scala:
  - 2.11.12
  - 2.12.7

jdk:
  - oraclejdk8

before_install:
  - ./install-redis.sh

env:
  global:
    - REDIS_VERSION=5.0.0
    - REDIS_HOME=$PWD/redis-$REDIS_VERSION/src
  matrix:
    - JOB="commons-jvm/test"
    - JOB="commons-js/test"
    - JOB="commons/unidoc"

script:
  - sbt ++$TRAVIS_SCALA_VERSION $JOB

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers/
    - redis-$REDIS_VERSION

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

notifications:
  email:
    - r.janusz@avsystem.com
