language: scala

scala:
  - 2.11.8
  - 2.12.0

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test commons/unidoc

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
