package com.avsystem.commons
package annotation

import scala.annotation.StaticAnnotation

/**
  * Used in code generated by macros which traverse sealed hierarchies using `knownDirectSubclasses`.
  * Allows the static analyzer to determine if `knownDirectSubclasses` used in macro returned correct
  * result (see <a href="https://issues.scala-lang.org/browse/SI-7046">SI-7046</a>).
  */
class checkKnownSubtypes[T](number: Int) extends StaticAnnotation
